"""create tables

Revision ID: 94b0b1e2fd36
Revises: 
Create Date: 2024-02-22 10:26:54.096650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94b0b1e2fd36'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('classificationLevel', sa.String(), nullable=False),
    sa.Column('preferredSkillsets', sa.String(), nullable=False),
    sa.Column('desiredDeliverable', sa.String(), nullable=False),
    sa.Column('organization', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('pocName', sa.String(), nullable=False),
    sa.Column('pocDiscordName', sa.String(), nullable=False),
    sa.Column('hasData', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('taskCode', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('isCompleted', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('pictureName', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('captainDiscordName', sa.String(), nullable=False),
    sa.Column('gitRepo', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('preferredWorkTime', sa.String(), nullable=False),
    sa.Column('classificationLevel', sa.String(), nullable=False),
    sa.Column('preferredSkillsets', sa.String(), nullable=False),
    sa.Column('needsMembers', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('captainCode', sa.String(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('pictureName', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('captainCode')
    )
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('discordName', sa.String(), nullable=False),
    sa.Column('skillsets', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    op.drop_table('teams')
    op.drop_table('tasks')
    # ### end Alembic commands ###
